Added code
Burnyaxa/lab_06_02 pull request #1
Opened 2018-11-16 16:25 UTC by Burnyaxa

@nechaido

2018-11-17 19:06 UTC, klitsunova approved these changes

2018-11-18 12:50 UTC, nechaido requested changes
Стилистическое замечание - разделяй функции пустой строкой.

2018-11-18 12:50 UTC, nechaido commented on 06_02.cpp
> +double arr_square[3];
Лучше не использовать глобальные переменные, а передавать необходимые данные как аргументы в функцию.

2018-11-18 12:50 UTC, nechaido commented on 06_02.cpp
> +double square(double A,double B,double C);
```suggestion
double area(double A,double B,double C);
```

2018-11-24 19:30 UTC, nechaido commented on 06_02.cpp
> +double arr_square[3];
Это до сих пор не решено.

2018-11-25 15:00 UTC, nechaido approved these changes
Принято.

2018-12-05 06:17 UTC, merged